version: '3.8'

services:
  openclaw:
    image: moltbot/moltbot:2026.1.24
    tty: true
    # --- MODO MANUTENÇÃO (Ativar para config inicial) ---
    # entrypoint: ["/bin/sh", "-c", "tail -f /dev/null"]

    # --- MODO PRODUÇÃO ---
    command: ["dist/index.js", "gateway", "--bind", "lan", "--port", "18789"]
    working_dir: /app
    user: root
    restart: always

    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - TZ=America/Sao_Paulo
      - OPENCLAW_GATEWAY_TOKEN=TokenInicial123
      - OPENCLAW_PK=TOKENTESTE
      - OPENCLAW_DOMAIN=${OPENCLAW_DOMAIN}
      - OPENCLAW_GATEWAY_BIND=lan
      - HOME=/root
      - OPENCLAW_GATEWAY_TRUST_PROXY=true
      - OPENCLAW_GATEWAY_EXTERNAL_URL=https://${OPENCLAW_DOMAIN}
      - OPENCLAW_GATEWAY_CORS_ALLOWED_ORIGINS=https://${OPENCLAW_DOMAIN}
      - OPENCLAW_GATEWAY_ALLOWED_ORIGINS=https://${OPENCLAW_DOMAIN}

    volumes:
      - openclaw_config:/root/.clawdbot
      - openclaw_workspace:/root/clawd

    networks:
      - traefik
      - clawdbot_internal

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      # Router
      - "traefik.http.routers.openclaw-rt.rule=Host(`${OPENCLAW_DOMAIN}`)"
      - "traefik.http.routers.openclaw-rt.entrypoints=websecure"
      - "traefik.http.routers.openclaw-rt.tls=true"
      - "traefik.http.routers.openclaw-rt.tls.certresolver=leresolver"

      # Middlewares (definição)
      - "traefik.http.middlewares.openclaw-cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE,PATCH"
      - "traefik.http.middlewares.openclaw-cors.headers.accesscontrolalloworiginlist=https://${OPENCLAW_DOMAIN}"
      - "traefik.http.middlewares.openclaw-cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.openclaw-cors.headers.accesscontrolallowcredentials=true"
      - "traefik.http.middlewares.openclaw-cors.headers.addvaryheader=true"
      - "traefik.http.middlewares.openclaw-auth.headers.customrequestheaders.Authorization=Bearer TokenInicial123"

      # Aplicação dos middlewares no router correto (openclaw-rt) com os nomes corretos
      - "traefik.http.routers.openclaw-rt.middlewares=openclaw-cors,openclaw-auth"

      # Service
      - "traefik.http.routers.openclaw-rt.service=openclaw-svc"
      - "traefik.http.services.openclaw-svc.loadbalancer.server.port=18789"

volumes:
  openclaw_config:
    external: false
  openclaw_workspace:
    external: false

networks:
  clawdbot_internal:
    external: true
  traefik:
    external: true